### ISSUE TITLE
Problem running script

### ISSUE THREAD

**Issue by Manso002** [Wanting-Dong/MetaVF_toolkit#2]
Hello!
I am trying to run the script on my viral_genomes file (.fna extension) with PE mode but I keep getting this error :

Traceback (most recent call last):
  File "/home/meridian/Softwares/MetaVF_toolkit/metaVF.py", line 68, in <module>
    main()
  File "/home/meridian/Softwares/MetaVF_toolkit/metaVF.py", line 56, in main
    write_yaml(args.direct_indata_path, yaml_file_name, args.project_name, direct_output_path, args.mode, args.thre_identity, args.thre_coverage)
  File "/home/meridian/Softwares/MetaVF_toolkit/metaVF.py", line 17, in write_yaml
    ("[%s]"%(reduce(lambda x,y: "%s,%s"%(x,y), list_names))\
TypeError: reduce() of empty sequence with no initial value

Hope you can help me!
Have a nice day!

Carlos

**Comment by Manso002** [comment]
Thank you so much. 

I should have read the help menu better. It worked, thanks!
